### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by RolandB00** [rubynor/bigfive-web#135]
Hey there,

I've followed the file readme in the folder "web" and opened the website, but when I try to click on "take the free test now" , the following error message is popping up:
TypeError: Cannot read properties of undefined (reading 'startsWith')

The console says:

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at addPathPrefix (add-path-prefix.js:13:15)
    at addBasePath (add-base-path.js:15:114)
    at eval (app-router.js:158:58)
    at eval (app-router.js:282:21)
    at startTransition (react.development.js:2597:25)
    at push (app-router.js:280:44)
    at handler (useBaseRouter.js:54:24)
    at eval (openLink.mjs:42:85)
    at $ea8dcbcb9ea1b556$var$getSyntheticLink (openLink.mjs:101:46)
    at Object.open (openLink.mjs:41:17)
    at onClick (index.mjs:51:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20703:25)
    at executeDispatch (react-dom.development.js:32128:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:32160:7)
    at processDispatchQueue (react-dom.development.js:32173:5)
    at dispatchEventsForPlugins (react-dom.development.js:32184:3)
    at eval (react-dom.development.js:32374:12)
    at batchedUpdates$1 (react-dom.development.js:24953:12)
    at batchedUpdates (react-dom.development.js:28844:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:32373:3)
    at dispatchEvent (react-dom.development.js:30141:5)
    at dispatchDiscreteEvent (react-dom.development.js:30112:5)

Can you please help me fix the issue?

Kind regards,

Roland

**Comment by hrmate** [comment]
Hi!
I am experiencing the same issue.

**Comment by manishverma3** [comment]
update @nextui-org/link to latest version
1. go to package.json and replace line 26 with "@nextui-org/link": "2.0.35"
2. delete node_modules
3. yarn or npm install
thats it.
